Final/WebAppliProyectoFinal/WebAppliProyectoFinal/Models/Doctor.cs
using System;
using System.Collections.Generic;

namespace WebAppliProyectoFinal.Models;

public partial class Doctor
{
    public int Iddoc { get; set; }

    public string? Nomdoc { get; set; }

    public string? Apedoc { get; set; }

    public string? Espdoc { get; set; }

    public int Celdoc { get; set; }

    public virtual ICollection<Citum> Cita { get; set; } = new List<Citum>();
}

Final/WebAppliProyectoFinal/WebAppliProyectoFinal/Controllers/DoctorController.cs
using Microsoft.AspNetCore.Mvc;
using System.Numerics;
using WebAppliProyectoFinal.Models;
using WebAppliProyectoFinal.Services;

namespace WebAppliProyectoFinal.Controllers
{
    public class DoctorController : Controller
    {
        private readonly IDoctor _doctor;

        public DoctorController(IDoctor doctor)
        {
            _doctor = doctor;
        }
        public IActionResult Index()
        {
            return View(_doctor.GetAllDoctor());
        }
        [Route("Doctor/Eliminar/{Id}")]
        public IActionResult eliminar(int id)
        {
            _doctor.remove(id);
            return RedirectToAction("Index");
        }
        public IActionResult nuevo()
        {
            return View();
        }
        public IActionResult grabar(Doctor doctor)
        {
            _doctor.add(doctor);
            return RedirectToAction("Index");
        }
        [Route("Doctor/Edit/{Id}")]
        public IActionResult Edit(int id)
        {
            return View(_doctor.edit(id));
        }
        public IActionResult editDoctor(Doctor obj)
        {
            _doctor.editaDetails(obj);
            return RedirectToAction("Index");
        }


    }
}

Final/WebAppliProyectoFinal/WebAppliProyectoFinal/Controllers/PortadaController.cs
using Microsoft.AspNetCore.Mvc;
using WebAppliProyectoFinal.Models;
using WebAppliProyectoFinal.Services;

namespace WebAppliProyectoFinal.Controllers
{
    public class PortadaController : Controller
    {
         private readonly IPortada _portada;
        public PortadaController(IPortada portada)
        {
            _portada = portada;
        }
        public IActionResult Index()
        {
            return View();
        }
        public IActionResult NueCar()
        {
            return View();
        }
        public IActionResult NueDer()
        {
            return View();
        }
        public IActionResult NuePed()
        {
            return View();
        }
        public IActionResult NueGine()
        {
            return View();
        }
        public IActionResult NueOnc()
        {
            return View();
        }
        public IActionResult NueOfta()
        {
            return View();
        }
        public IActionResult NueNeu()
        {
            return View();
        }
        public IActionResult NueMedGe()
        {
            return View();
        }
        public IActionResult Revisar()
        {
            return View();
        }
        public IActionResult Doctor()
        {
            return View();
        }

    }
}

Final/WebAppliProyectoFinal/WebAppliProyectoFinal/Views/Doctor/Edit.cshtml
@model WebAppliProyectoFinal.Models.Doctor
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}
<html>
<head>
</head>
<body>
    <div class="boxProducto">

        <h1>Editar Doctor</h1>

    <form asp-controller="Doctor" asp-action="editDoctor" method="post">
        <input type="hidden" asp-for="Iddoc" />
        <br />
            Nombre:<input type="text" asp-for="Nomdoc" placeholder="Ingrese el nuevo Nombre del Paciente" required />
        <br />
            Apellido:<input type="text" asp-for="Apedoc" placeholder="Ingrese el nuevo Apellido del Paciente" required />
        <br />
            Especialidad:<input type="text" asp-for="Espdoc" placeholder="Ingrese el nuevo Correo del Paciente" required />
        <br />
            Celular:<input type="text" asp-for="Celdoc" placeholder="Ingresar el nuevo DNI de telefono del Paciente" required />
            <br />
            
            <input type="submit" class="btn btn-success" value="Editar" />
            <a asp-action="Index" class="btn btn-primary m-2">Salir</a>

    </form>
        
    </div>

</body>
</html>

Final/WebAppliProyectoFinal/WebAppliProyectoFinal/Views/Doctor/Index.cshtml
@model IEnumerable<WebAppliProyectoFinal.Models.Doctor>
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}
<html>

    <head>

    </head>
    <body>
        <h1>Lista de Doctores Actuales</h1>
        <div class="boxProducto">
        
            <a class="btn btn-success mx-auto" asp-controller="Doctor" asp-action="Nuevo">Nuevos Doctores</a>
            
            <a class="btn btn-danger mx-auto" asp-controller="Portada" asp-action="Index">Salir</a>

                @foreach (var item in Model)
                {
                

                    <div class="card m-5" style="min-width:18rem;max-width:30.5%;">
                        <div class="card-header">
                        <h5>Nombre: <strong>@item.Nomdoc</strong></h5>
                        <h5>Apellido: <strong>@item.Apedoc</strong></h5>
                        <h5>Especialidad: <strong>@item.Espdoc</strong></h5>
                        <h5>Cell: <strong>@item.Celdoc</strong></h5>
                        </div>
                        <div class="card-footer text-center">

                            <a asp-action="Edit" asp-route-id="@item.Iddoc" class="btn btn-primary m-2">Editar</a>
                        <a class="btn btn-outline-danger" asp-action="eliminar" asp-route-id="@item.Iddoc">Eliminar Doctor</a>
                        </div>
                    </div>
                }


        </div>


    </body>


</html>

Final/WebAppliProyectoFinal/WebAppliProyectoFinal/Views/Doctor/Nuevo.cshtml
@model WebAppliProyectoFinal.Models.Doctor
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}
<html>
    <head>

    </head>
    <body >

        

        <div class="boxProducto">

        <h1>Nuevos Doctores</h1>
            <form asp-controller="Doctor" asp-action="grabar" method="post">

                <input type="hidden" asp-for="Iddoc" required />
                    <br />
                    Nombre:<input type="text" asp-for="Nomdoc" placeholder="Ingrese el nombre del Doctor" required />
                    <br />
                    Apellido:<input type="text" asp-for="Apedoc" placeholder="Ingrese el apellido del Doctor" required />
                    <br />
                    
                    Especialidad:<input type="text" asp-for="Espdoc" placeholder="Ingrese la Especialidad del Doctor" required />
                    <br />
                    Celular:<input type="text" asp-for="Celdoc" placeholder="Ingresar el Celular del Doctor" required />
                    <br />

                <input type="submit" class="btn btn-success" value="Grabar" />
                <a asp-action="Index" class="btn btn-primary m-2">Salir</a>

            </form>
        </div>
    </body>

</html>