Final/WebAppliProyectoFinal/WebAppliProyectoFinal/Models/Paciente.cs
using System;
using System.Collections.Generic;

namespace WebAppliProyectoFinal.Models;

public partial class Paciente
{
    public int Idpa { get; set; }

    public string? Nompa { get; set; }

    public string? Apepa { get; set; }

    public string? Corpa { get; set; }

    public int Dnipa { get; set; }

    public int Celpa { get; set; }

    public virtual ICollection<Citum> Cita { get; set; } = new List<Citum>();
}

Final/WebAppliProyectoFinal/WebAppliProyectoFinal/Controllers/PacienteController.cs
using Microsoft.AspNetCore.Mvc;
using WebAppliProyectoFinal.Models;
using WebAppliProyectoFinal.Services;

namespace WebAppliProyectoFinal.Controllers
{
    public class PacienteController : Controller
    {
        private readonly IPaciente _paciente;
        public PacienteController(IPaciente paciente)
        {
            _paciente = paciente;
        }
        public IActionResult Index()
        {
            return View(_paciente.GetAllPacientes());
        }
        [Route("Paciente/Eliminar/{Id}")]
        public IActionResult eliminar(int id) 
        {
            _paciente.remove(id);
            return RedirectToAction("Index");
        }
        public IActionResult nuevo()
        {
            return View();
        }
        public IActionResult grabar(Paciente paciente)
        {
            _paciente.add(paciente);
            return RedirectToAction("Doctor","Index");
        }
        [Route("Paciente/Edit/{Id}")]
        public IActionResult Edit(int id)
        {
            return View(_paciente.edit(id));
        }
        public IActionResult editPaciente(Paciente obj)
        {
            _paciente.EditDatails(obj);
            return RedirectToAction("Index");
        }



    }
}

Final/WebAppliProyectoFinal/WebAppliProyectoFinal/Controllers/PortadaController.cs
using Microsoft.AspNetCore.Mvc;
using WebAppliProyectoFinal.Models;
using WebAppliProyectoFinal.Services;

namespace WebAppliProyectoFinal.Controllers
{
    public class PortadaController : Controller
    {
         private readonly IPortada _portada;
        public PortadaController(IPortada portada)
        {
            _portada = portada;
        }
        public IActionResult Index()
        {
            return View();
        }
        public IActionResult NueCar()
        {
            return View();
        }
        public IActionResult NueDer()
        {
            return View();
        }
        public IActionResult NuePed()
        {
            return View();
        }
        public IActionResult NueGine()
        {
            return View();
        }
        public IActionResult NueOnc()
        {
            return View();
        }
        public IActionResult NueOfta()
        {
            return View();
        }
        public IActionResult NueNeu()
        {
            return View();
        }
        public IActionResult NueMedGe()
        {
            return View();
        }
        public IActionResult Revisar()
        {
            return View();
        }
        public IActionResult Doctor()
        {
            return View();
        }

    }
}

Final/WebAppliProyectoFinal/WebAppliProyectoFinal/Views/Paciente/Edit.cshtml
@model WebAppliProyectoFinal.Models.Paciente
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}
<html>
<head>
</head>
<body>
    <div class="tabla">
    </div>
    <form asp-controller="Paciente" asp-action="editPaciente" method="post">
        <input type="hidden" asp-for="Idpa" />
        <br />
        Nombre:<input type="text" asp-for="Nompa" placeholder="Ingrese el nuevo Nombre del Paciente" required />
        <br />
        Apellido:<input type="text" asp-for="Apepa" placeholder="Ingrese el nuevo Apellido del Paciente" required />
        <br />
        Correo:<input type="text" asp-for="Corpa" placeholder="Ingrese el nuevo Correo del Paciente" required />
        <br />
        DNI:<input type="text" asp-for="Dnipa" placeholder="Ingresar el nuevo DNI de telefono del Paciente" required />
        <br />
        Celular:<input type="text" asp-for="Celpa" placeholder="Ingresar el nuevo Celular del Paciente" required />
        <br />
        <input type="submit" class="btn btn-success" value="Editar" />
        <a asp-action="Index" class="btn btn-primary m-2">Salir</a>
    </form>
</body>
</html>

Final/WebAppliProyectoFinal/WebAppliProyectoFinal/Views/Paciente/Index.cshtml
@model IEnumerable<WebAppliProyectoFinal.Models.Paciente>
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}
<html>

<head>

</head>
<body>
    <h1>Lista de Pacientes Actuales en el Sistema</h1>
    <div class="boxProducto">

        
        <a class="btn btn-danger mx-auto" asp-controller="Portada" asp-action="Index">Salir</a>

        @foreach (var item in Model)
        {


            <div class="card m-5" style="min-width:18rem;max-width:30.5%;">
                <div class="card">
                    <h5>Nombre: <strong>@item.Nompa</strong></h5>
                    <h5>Apellido: <strong>@item.Apepa</strong></h5>
                    <h5>Correo: <strong>@item.Corpa</strong></h5>
                    <h5>DNI: <strong>@item.Dnipa</strong></h5>
                    <h5>Celular: <strong>@item.Celpa</strong></h5>
                </div>
                <div class="card-footer text-center">
                     
                    <a asp-action="Edit" asp-route-id="@item.Idpa" class="btn btn-primary m-2">Editar</a>
                    <a class="btn btn-outline-danger" asp-action="eliminar" asp-route-id="@item.Idpa">Eliminar Doctor</a>
                </div>
            </div>
        }


    </div>


</body>


</html>

Final/WebAppliProyectoFinal/WebAppliProyectoFinal/Views/Paciente/Nuevo.cshtml
@model WebAppliProyectoFinal.Models.Paciente
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}
<html>
    <head>
    </head>

    <body>
        <form asp-controller="Paciente" asp-action="grabar" method="post">
            <input type="hidden" asp-for="Idpa" required />
            Nombre:<input type="text" asp-for="Nompa" placeholder="Ingrese el nombre del Paciente" required />
            Apellido:<input type="text" asp-for="Apepa" placeholder="Ingrese el apellido del Paciente" required />
            Correo:<input type="text" asp-for="Corpa" placeholder="Ingrese el Correo del Paciente" required />
            DNI:<input type="text" asp-for="Dnipa" placeholder="Ingresar el DNI del Paciente" required />
            Celular:<input type="text" asp-for="Celpa" placeholder="Ingrese el numero celular del Paciente" required />

            <input type="submit" value="Grabar" />
        </form>
    </body>
</html>