Final/WebAppliProyectoFinal/WebAppliProyectoFinal/Controllers/CitaController.cs
using Microsoft.AspNetCore.Mvc;

namespace WebAppliProyectoFinal.Controllers
{
    public class CitaController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }
    }
}

Final/WebAppliProyectoFinal/WebAppliProyectoFinal/Controllers/DoctorController.cs
using Microsoft.AspNetCore.Mvc;
using System.Numerics;
using WebAppliProyectoFinal.Models;
using WebAppliProyectoFinal.Services;

namespace WebAppliProyectoFinal.Controllers
{
    public class DoctorController : Controller
    {
        private readonly IDoctor _doctor;

        public DoctorController(IDoctor doctor)
        {
            _doctor = doctor;
        }
        public IActionResult Index()
        {
            return View(_doctor.GetAllDoctor());
        }
        [Route("Doctor/Eliminar/{Id}")]
        public IActionResult eliminar(int id)
        {
            _doctor.remove(id);
            return RedirectToAction("Index");
        }
        public IActionResult nuevo()
        {
            return View();
        }
        public IActionResult grabar(Doctor doctor)
        {
            _doctor.add(doctor);
            return RedirectToAction("Index");
        }
        [Route("Doctor/Edit/{Id}")]
        public IActionResult Edit(int id)
        {
            return View(_doctor.edit(id));
        }
        public IActionResult editDoctor(Doctor obj)
        {
            _doctor.editaDetails(obj);
            return RedirectToAction("Index");
        }


    }
}

Final/WebAppliProyectoFinal/WebAppliProyectoFinal/Controllers/PacienteController.cs
using Microsoft.AspNetCore.Mvc;
using WebAppliProyectoFinal.Models;
using WebAppliProyectoFinal.Services;

namespace WebAppliProyectoFinal.Controllers
{
    public class PacienteController : Controller
    {
        private readonly IPaciente _paciente;
        public PacienteController(IPaciente paciente)
        {
            _paciente = paciente;
        }
        public IActionResult Index()
        {
            return View(_paciente.GetAllPacientes());
        }
        [Route("Paciente/Eliminar/{Id}")]
        public IActionResult eliminar(int id) 
        {
            _paciente.remove(id);
            return RedirectToAction("Index");
        }
        public IActionResult nuevo()
        {
            return View();
        }
        public IActionResult grabar(Paciente paciente)
        {
            _paciente.add(paciente);
            return RedirectToAction("Doctor","Index");
        }
        [Route("Paciente/Edit/{Id}")]
        public IActionResult Edit(int id)
        {
            return View(_paciente.edit(id));
        }
        public IActionResult editPaciente(Paciente obj)
        {
            _paciente.EditDatails(obj);
            return RedirectToAction("Index");
        }



    }
}

Final/WebAppliProyectoFinal/WebAppliProyectoFinal/Controllers/PortadaController.cs
using Microsoft.AspNetCore.Mvc;
using WebAppliProyectoFinal.Models;
using WebAppliProyectoFinal.Services;

namespace WebAppliProyectoFinal.Controllers
{
    public class PortadaController : Controller
    {
         private readonly IPortada _portada;
        public PortadaController(IPortada portada)
        {
            _portada = portada;
        }
        public IActionResult Index()
        {
            return View();
        }
        public IActionResult NueCar()
        {
            return View();
        }
        public IActionResult NueDer()
        {
            return View();
        }
        public IActionResult NuePed()
        {
            return View();
        }
        public IActionResult NueGine()
        {
            return View();
        }
        public IActionResult NueOnc()
        {
            return View();
        }
        public IActionResult NueOfta()
        {
            return View();
        }
        public IActionResult NueNeu()
        {
            return View();
        }
        public IActionResult NueMedGe()
        {
            return View();
        }
        public IActionResult Revisar()
        {
            return View();
        }
        public IActionResult Doctor()
        {
            return View();
        }

    }
}

Final/WebAppliProyectoFinal/WebAppliProyectoFinal/Controllers/UsuarioController.cs
using Microsoft.AspNetCore.Mvc;
using WebAppliProyectoFinal.Models;
using WebAppliProyectoFinal.Services;

namespace WebAppliProyectoFinal.Controllers
{
    public class UsuarioController : Controller
    {
        private readonly IUsuario _usuario;
        public UsuarioController(IUsuario usuario)
        {
            _usuario = usuario;
        }
        public IActionResult Index()
        {
            return View();
        }
        public IActionResult Principal()
        {
            return View();
        }
        public IActionResult Info()
        {
            return View();
        }
        public IActionResult validarUsuario(Usuario obj)
        {
            if (_usuario.ValidateUser(obj) == true)
            {
                return RedirectToAction("Index","Portada");
            }
            else
            {
                return View("Index");
            }

        }
        public IActionResult Nuevo()
        {
            return View();
        }
        public IActionResult Grabar(Usuario obj)
        {
            _usuario.add(obj);
            return RedirectToAction("Index");
        }



    }
}

Final/WebAppliProyectoFinal/WebAppliProyectoFinal/Views/Portada/Index.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
   
}
<html>

<head>

</head>
<body>


    <h1 class="">Especialidades</h1>



    <div class="boxProducto">
        
        <div>
            <a class="btn btn-success mx-auto" asp-controller="Doctor" asp-action="Index">Doctores</a>
            <a class="btn btn-success" asp-controller="Paciente" asp-action="Index">Editar Paciente</a>
            <a class="btn btn-success" asp-controller="Cita" asp-action="Index">Revisar Citas</a>
            <a class="btn btn-danger mx-auto" asp-controller="Usuario" asp-action="Index">Salir</a>
        </div>




        <form asp-controller="Portada" asp-action="NuePaciente">


            <div class="container px-4 px-lg-5 mt-5">


                <div class="row gx-4 gx-lg-5 row-cols-2 row-cols-md-3 row-cols-xl-4 justify-content-center">

                    <div class="col mb-5">
                        <div class="card h-100">
                            <!-- Product image-->
                            <img class="card-img-top" src="img/cardiologia.jpg" alt="..." />
                            <!-- Product details-->
                            <div class="card-body p-4">
                                <div class="text-center">
                                    <!-- Product name-->
                                    <h5 class="fw-bolder">Cardiologia</h5>
                                </div>
                            </div>


                            <div class="card-footer p-4 pt-0 border-top-0 bg-transparent">

                                <div class="text-center"><a class="btn btn-outline-dark mt-auto" asp-controller="Portada" asp-action="NueCar">Solicitar Cita</a></div>

                            </div>



                        </div>
                    </div>


                    <div class="col mb-5">
                        <div class="card h-100">
                            <!-- Product image-->
                            <img class="card-img-top" src="img/derma.jpg" alt="..." />
                            <!-- Product details-->
                            <div class="card-body p-4">
                                <div class="text-center">
                                    <!-- Product name-->
                                    <h5 class="fw-bolder">Dermatologia</h5>
                                </div>
                            </div>
                            <!-- Product actions-->
                            <div class="card-footer p-4 pt-0 border-top-0 bg-transparent">
                                <div class="text-center"><a class="btn btn-outline-dark mt-auto" asp-controller="Portada" asp-action="NueDer">Solicitar Cita</a></div>
                            </div>
                        </div>
                    </div>
                    <div class="col mb-5">
                        <div class="card h-100">
                            <!-- Product image-->
                            <img class="card-img-top" src="img/pediatria.jpg" alt="..." />
                            <!-- Product details-->
                            <div class="card-body p-4">
                                <div class="text-center">
                                    <!-- Product name-->
                                    <h5 class="fw-bolder">Pediatria</h5>
                                </div>
                            </div>
                            <!-- Product actions-->
                            <div class="card-footer p-4 pt-0 border-top-0 bg-transparent">
                                <div class="text-center"><a class="btn btn-outline-dark mt-auto" asp-controller="Portada" asp-action="NuePed">Solicitar Cita</a></div>
                            </div>
                        </div>
                    </div>
                    <div class="col mb-5">
                        <div class="card h-100">
                            <!-- Product image-->
                            <img class="card-img-top" src="img/ginec.jpg" alt="..." />
                            <!-- Product details-->
                            <div class="card-body p-4">
                                <div class="text-center">
                                    <!-- Product name-->
                                    <h5 class="fw-bolder">Ginecologia</h5>
                                </div>
                            </div>
                            <!-- Product actions-->
                            <div class="card-footer p-4 pt-0 border-top-0 bg-transparent">
                                <div class="text-center"><a class="btn btn-outline-dark mt-auto" asp-controller="Portada" asp-action="NueGine">Solicitar Cita</a></div>
                            </div>
                        </div>
                    </div>
                    <div class="col mb-5">
                        <div class="card h-100">
                            <!-- Product image-->
                            <img class="card-img-top" src="img/onco.jpg" alt="..." />
                            <!-- Product details-->
                            <div class="card-body p-4">
                                <div class="text-center">
                                    <!-- Product name-->
                                    <h5 class="fw-bolder">Oncologia</h5>
                                </div>
                            </div>
                            <!-- Product actions-->
                            <div class="card-footer p-4 pt-0 border-top-0 bg-transparent">
                                <div class="text-center"><a class="btn btn-outline-dark mt-auto" asp-controller="Portada" asp-action="NueOnc">Solicitar Cita</a></div>
                            </div>
                        </div>
                    </div>
                    <div class="col mb-5">
                        <div class="card h-100">
                            <!-- Product image-->
                            <img class="card-img-top" src="img/oftal.jpg" alt="..." />
                            <!-- Product details-->
                            <div class="card-body p-4">
                                <div class="text-center">
                                    <!-- Product name-->
                                    <h5 class="fw-bolder">Oftaltologia</h5>
                                </div>
                            </div>
                            <!-- Product actions-->
                            <div class="card-footer p-4 pt-0 border-top-0 bg-transparent">
                                <div class="text-center"><a class="btn btn-outline-dark mt-auto" asp-controller="Portada" asp-action="NueOfta">Solicitar Cita</a></div>
                            </div>
                        </div>
                    </div>
                    <div class="col mb-5">
                        <div class="card h-100">
                            <!-- Product image-->
                            <img class="card-img-top" src="img/Neurología.jpg" alt="..." />
                            <!-- Product details-->
                            <div class="card-body p-4">
                                <div class="text-center">
                                    <!-- Product name-->
                                    <h5 class="fw-bolder">Neurologia</h5>
                                </div>
                            </div>
                            <!-- Product actions-->
                            <div class="card-footer p-4 pt-0 border-top-0 bg-transparent">
                                <div class="text-center"><a class="btn btn-outline-dark mt-auto" asp-controller="Portada" asp-action="NueNeu">Solicitar Cita</a></div>
                            </div>
                        </div>
                    </div>
                    <div class="col mb-5">
                        <div class="card h-100">
                            <!-- Product image-->
                            <img class="card-img-top" src="img/med.jpg" alt="..." />
                            <!-- Product details-->
                            <div class="card-body p-4">
                                <div class="text-center">
                                    <!-- Product name-->
                                    <h5 class="fw-bolder">Medicina General</h5>
                                </div>
                            </div>
                            <!-- Product actions-->
                            <div class="card-footer p-4 pt-0 border-top-0 bg-transparent">
                                <div class="text-center"><a class="btn btn-outline-dark mt-auto" asp-controller="Portada" asp-action="NueMedGe">Solicitar Cita</a></div>
                            </div>
                        </div>
                    </div>




                </div>

            </div>

        </form>

    </div>





</body>

</html>

Final/WebAppliProyectoFinal/WebAppliProyectoFinal/Views/Portada/NueCar.cshtml
@model WebAppliProyectoFinal.Models.Paciente
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}
<html>
    <head>

    </head>
    <body>
        <div class="boxProducto">
            <form asp-controller="Paciente" asp-action="Grabar" method="post">

                
                <h1 style="text-align: center;" class="alert alert-success">Nueva Cita Cardiología</h1>
                <br />
                <h1>Datos del Paciente</h1>
            <br />

                Nombre:<input type="text" asp-for="Nompa" placeholder="Ingrese el nombre del Paciente" required />
                <br />

                Apellido:<input type="text" asp-for="Apepa" placeholder="Ingrese el apellido del Paciente" required />
            <br />

                Correo:<input type="text" asp-for="Corpa" placeholder="Ingrese el Correo del Paciente" required />

            <br />
                DNI:<input type="text" asp-for="Dnipa" placeholder="Ingresar el DNI del Paciente" required />
            <br />

                Celular:<input type="text" asp-for="Celpa" placeholder="Ingrese el numero celular del Paci  ente" required />
            <br />

            <input type="submit" class="btn btn-success" value="Grabar" />
            <a asp-action="Index" class="btn btn-primary m-2">Salir</a>
            </form>
        </div>
    </body>
</html>

Final/WebAppliProyectoFinal/WebAppliProyectoFinal/Views/Portada/NueDer.cshtml
@model WebAppliProyectoFinal.Models.Paciente

@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}
<html>
<head>

</head>
<body>
    <div class="boxProducto">
        <form asp-controller="Portada" asp-action="Grabar" method="post">

            <h1 style="text-align: center;" class="alert alert-success">Nueva Cita Dermatologia</h1>

            <br />

            <label>Doctora</label>
            <h1>Gonzales Rioja, Josefina</h1>

            <label>ID del Doctor</label>
            <h1>34929</h1>


            <label>ID del Paciente</label>
            <br />
            <input type="text" class="form-control" asp-for="Idpa" required />
            <br /><br />
            <label>Nombre del Paciente</label>
            <br />
            <input type="text" class="form-control" asp-for="Nompa" />

            <br /><br />
            <label>Apellido del Paciente</label>
            <br />
            <input type="text" class="form-control" asp-for="Apepa" />

            <br /><br />




            <hr /><br />

            <div style="text-align: center;" class="d-grid gap-2 col-6 mx-auto">
                <input type="submit" class="btn btn-success" value="Solicitar cita">
            </div>

        </form>
    </div>
</body>

</html>

Final/WebAppliProyectoFinal/WebAppliProyectoFinal/Views/Portada/NueGine.cshtml
@model WebAppliProyectoFinal.Models.Paciente

@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}
<html>
<head>

</head>
<body>
    <div class="boxProducto">
        <form asp-controller="Portada" asp-action="Grabar" method="post">

            <h1 style="text-align: center;" class="alert alert-success">Nueva Cita Ginecologia</h1>

            <br />

            <label>Doctora</label>
            <h1>Huayta Camacho, Rosa Maria</h1>

            <label>ID del Doctor</label>
            <h1>37547</h1>


            <label>ID del Paciente</label>
            <br />
            <input type="text" class="form-control" asp-for="Idpa" required />
            <br /><br />
            <label>Nombre del Paciente</label>
            <br />
            <input type="text" class="form-control" asp-for="Nompa" />

            <br /><br />
            <label>Apellido del Paciente</label>
            <br />
            <input type="text" class="form-control" asp-for="Apepa" />

            <br /><br />




            <hr /><br />

            <div style="text-align: center;" class="d-grid gap-2 col-6 mx-auto">
                <input type="submit" class="btn btn-success" value="Solicitar cita">
            </div>


        </form>
    </div>
</body>

</html>

Final/WebAppliProyectoFinal/WebAppliProyectoFinal/Views/Portada/NueMedGe.cshtml
@model WebAppliProyectoFinal.Models.Paciente

@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}
<html>
<head>

</head>
<body>
    <div class="boxProducto">
        <form asp-controller="Portada" asp-action="Grabar" method="post">

            <h1 style="text-align: center;" class="alert alert-success">Nueva Cita Medicina General</h1>

            <br />

            <label>Doctora</label>
            <h1>Pardo Salvatierra, Ximena Alessandra</h1>

            <label>ID del Doctor</label>
            <h1>78383</h1>


            <label>ID del Paciente</label>
            <br />
            <input type="text" class="form-control" asp-for="Idpa" required />
            <br /><br />
            <label>Nombre del Paciente</label>
            <br />
            <input type="text" class="form-control" asp-for="Nompa" />

            <br /><br />
            <label>Apellido del Paciente</label>
            <br />
            <input type="text" class="form-control" asp-for="Apepa" />

            <br /><br />



            <hr /><br />

            <div style="text-align: center;" class="d-grid gap-2 col-6 mx-auto">
                <input type="submit" class="btn btn-success" value="Solicitar cita">
            </div>

        </form>
    </div>
</body>

</html>

Final/WebAppliProyectoFinal/WebAppliProyectoFinal/Views/Portada/NueNeu.cshtml
@model WebAppliProyectoFinal.Models.Paciente

@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}
<html>
<head>

</head>
<body>
    <div class="boxProducto">
        <form asp-controller="Portada" asp-action="Grabar" method="post">

            <h1 style="text-align: center;" class="alert alert-success">Nueva Cita Neurologia</h1>

            <br />

            <label>Doctor</label>
            <h1>Vega del Rosario, César Gonzalo</h1>

            <label>ID del Doctor</label>
            <h1>38574</h1>

            <label>ID del Paciente</label>
            <br />
            <input type="text" class="form-control" asp-for="Idpa" required />
            <br /><br />
            <label>Nombre del Paciente</label>
            <br />
            <input type="text" class="form-control" asp-for="Nompa" />

            <br /><br />
            <label>Apellido del Paciente</label>
            <br />
            <input type="text" class="form-control" asp-for="Apepa" />

            <br /><br />




            <hr /><br />

            <div style="text-align: center;" class="d-grid gap-2 col-6 mx-auto">
                <input type="submit" class="btn btn-success" value="Solicitar cita">
            </div>


        </form>
    </div>
</body>

</html>

Final/WebAppliProyectoFinal/WebAppliProyectoFinal/Views/Portada/NueOfta.cshtml
@model WebAppliProyectoFinal.Models.Paciente


@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}
<html>
<head>

</head>
<body>
    <div class="boxProducto">
        <form asp-controller="Portada" asp-action="Grabar" method="post">

            <h1 style="text-align: center;" class="alert alert-success">Nueva Cita Oftaltologia</h1>

            <br />

            <label>Doctora</label>
            <h1>Miranda Paredes, Luana Carolina</h1>

            <label>ID del Doctor</label>
            <h1>37474</h1>


            <label>ID del Paciente</label>
            <br />
            <input type="text" class="form-control" asp-for="Idpa" required />
            <br /><br />
            <label>Nombre del Paciente</label>
            <br />
            <input type="text" class="form-control" asp-for="Nompa" />

            <br /><br />
            <label>Apellido del Paciente</label>
            <br />
            <input type="text" class="form-control" asp-for="Apepa" />

            <br /><br />




            <hr /><br />

            <div style="text-align: center;" class="d-grid gap-2 col-6 mx-auto">
                <input type="submit" class="btn btn-success" value="Solicitar cita">
            </div>


        </form>
    </div>
</body>

</html>

Final/WebAppliProyectoFinal/WebAppliProyectoFinal/Views/Portada/NueOnc.cshtml
@model WebAppliProyectoFinal.Models.Paciente

@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}
<html>
<head>

</head>
<body>
    <div class="boxProducto">
        <form asp-controller="Portada" asp-action="Grabar" method="post">

            <h1 style="text-align: center;" class="alert alert-success">Nueva Cita Oncologia</h1>

            <br />

            <label>Doctor</label>
            <h1>Figueroa Castillo, Luis Alberto</h1>

            <label>ID del Doctor</label>
            <h1>34233</h1>


            <label>ID del Paciente</label>
            <br />
            <input type="text" class="form-control" asp-for="Idpa" required />
            <br /><br />
            <label>Nombre del Paciente</label>
            <br />
            <input type="text" class="form-control" asp-for="Nompa" />

            <br /><br />
            <label>Apellido del Paciente</label>
            <br />
            <input type="text" class="form-control" asp-for="Apepa" />

            <br /><br />




            <hr /><br />

            <div style="text-align: center;" class="d-grid gap-2 col-6 mx-auto">
                <input type="submit" class="btn btn-success" value="Solicitar cita">
            </div>


        </form>
    </div>
</body>

</html>

Final/WebAppliProyectoFinal/WebAppliProyectoFinal/Views/Portada/NuePed.cshtml
@model WebAppliProyectoFinal.Models.Paciente


@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}
<html>
<head>

</head>
<body>
    <div class="boxProducto">
        <form asp-controller="Portada" asp-action="Grabar" method="post">

            <h1 style="text-align: center;" class="alert alert-success">Nueva Cita Pediatria</h1>

            <br />

            <label>Doctor</label>
            <h1>Bohórquez Pariona, Pedro </h1>

            <label>ID del Doctor</label>
            <h1>38273</h1>

            <label>ID del Paciente</label>
            <br />
            <input type="text" class="form-control" asp-for="Idpa" required />
            <br /><br />
            <label>Nombre del Paciente</label>
            <br />
            <input type="text" class="form-control" asp-for="Nompa" />

            <br /><br />
            <label>Apellido del Paciente</label>
            <br />
            <input type="text" class="form-control" asp-for="Apepa" />

            <br /><br />




            <hr /><br />

            <div style="text-align: center;" class="d-grid gap-2 col-6 mx-auto">
                <input type="submit" class="btn btn-success" value="Solicitar cita">
            </div>


        </form>
    </div>
</body>

</html>